package com.minio.storage.enums;

public enum ActivityType {
    LOGIN,
    LOGOUT,
    REGISTER,
    RESEND_VERIFICATION,
    EMAIL_VERIFIED,
    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET_SUCCESS,

    FILE_UPLOAD,
    FILE_DOWNLOAD,
    FILE_DELETE,
    FILE_UPDATE,
    FILE_VIEW,
    FILE_PREVIEW,

    SHARE_CREATE,
    SHARE_ACCESS,
    SHARE_DELETE,

    BUCKET_CREATE,
    BUCKET_DELETE,
    BUCKET_UPDATE,
    BUCKET_SYNC,
    BUCKET_STATS_RECALCULATED,
    BUCKET_ORPHAN_AUDIT,

    USER_CREATE,
    USER_UPDATE,
    USER_DELETE
}