package com.minio.storage.enums;

public enum FileCategory {
    IMAGE,      // jpg, png, gif, svg, webp...
    DOCUMENT,   // pdf, docx, txt, xlsx...
    VIDEO,      // mp4, avi, mkv, mov...
    AUDIO,      // mp3, wav, flac, aac...
    ARCHIVE,    // zip, rar, tar, 7z...
    OTHER       // sve ostalo
}
